# Generated by Django 5.0.6 on 2024-06-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('idParticipante', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=8)),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('dataNascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
