# Generated by Django 5.0.6 on 2024-09-25 21:44

import participante.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='imagem',
            field=models.ImageField(upload_to=participante.models.faces_participantes_path),
        ),
        migrations.AlterField(
            model_name='participante',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
